# This is a basic workflow to help you get started with Actions

name: building

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build toolchain
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
              brew install coreutils
        fi
        echo SRCDIR $SRCDIR BUILDDIR $BUILDDIR TARGETMACH $TARGETMACH BUILDMACH $BUILDMACH HOSTMACH $HOSTMACH INSTALLDIR $INSTALLDIR SYSROOTDIR $SYSROOTDIR ROOTDIR $ROOTDIR DOWNLOADDIR $DOWNLOADDIR PROGRAM_PREFIX $PROGRAM_PREFIX
        wget http://ftp.br.debian.org/debian/pool/main/a/automake-1.16/automake_1.16.1-4_all.deb
        sudo apt-get -y install ./automake_1.16.1-4_all.deb
        sudo apt-get install autoconf-archive
        ./build-elf.sh
      env: 
        SRCDIR: ${{ github.workspace }}/source
        BUILDDIR:  ${{ github.workspace }}/build
        TARGETMACH: sh-elf
        BUILDMACH: x86_64-pc-linux-gnu
        HOSTMACH: x86_64-pc-linux-gnu
        INSTALLDIR:  ${{ github.workspace }}/toolchain
        SYSROOTDIR: ${{ github.workspace }}/toolchain/sysroot
        ROOTDIR:  ${{ github.workspace }}
        DOWNLOADDIR:  ${{ github.workspace }}/download
        PROGRAM_PREFIX: saturn-sh2-
        NCPU: 2
